### ISSUE TITLE
Provide a secret that contains the credentials and connectivity information for the DB2 warehouse instance

### ISSUE THREAD

**Issue by seansund** [cloud-native-toolkit/terraform-gitops-cp-db2wh#19]
Once DB2 warehouse has been provisioned we need the connection information for the instance. There are five pieces of information required:

- host
- port
- database name
- username
- password

The way to store/pass this information in the cluster is via a secret.

- [ ] Create a secret that contains the required information (ideally this secret already exists but if not a job is needed to create it). The host can be the internal service DNS name (`{service name}.{namespace}.svc`)
- [ ] Add the following outputs to the module
    - `secret_name` - the name of the secret that contains the connectivity information
    - `host_key` - the key in the secret that contains the host information (e.g. "host")
    - `port_key` - the key in the secret that contains the port information
    - `database_key` - the key in the secret that contains the database name information
    - `username_key` - the key in the secret that contains the username information
    - `password_key` - the key in the secret that contains the password information
- [ ] Add the interface definition to the module metadata

    ```
    name: gitops-cp-db2wh
    type: terraform
    interfaces:
      - github.com/cloud-native-toolkit/automation-modules#database-secret
    ```
